### PR TITLE
Module 1 : Portfolio Mobile Menu

### PR DESCRIPTION
**Pull request by ikennarichard**
## Module 1 (Week 4): Portfolio Mobile Menu
For this project, I
- Made use of the HTML, CSS and JavaScript Linters
- Used JavaScript to display/hide the mobile menu when the hamburger button is clicked
- Edited the 'Welcome' logo animation
- Worked with my coding partner to update page styles
- Made the page to go to the correct section of the mobile menu options
- I used JavaScript to toggle the hamburger button

### CODE REVIEW

**Review by vickymarz — APPROVED** [review]
Hi  @ikennarichard, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Good UI design✅ 
- Mobile menu functionality working well ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vickymarz** [comment]
Hello, ikenna, i reverted the approval of your pull request because you
pushed commits that has failed linter test. Please unmerge or do something

**Comment by vickymarz** [comment]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project that has failed linter check, and you have already merged the pull request. Kindly fix your linter errors, create a new pull request and submit again 👍🏽 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ikennarichard** [comment]
Please which of the linters is failing, I can't find it on my pull request @vickymarz

**Comment by ikennarichard** [comment]
Please which of the linters is failing, I can't find it on my pull request @vickymarz

**Comment by vickymarz** [comment]
Your last commit , Add transition to social links

**Comment by ikennarichard** [comment]
Please I don't quite understand, my last commit was the fix stylint issues commit with @vickymarz 
last_commit_3

**Comment by vickymarz** [comment]
This is the last commit that failed linter check

**Comment by ikennarichard** [comment]
The add transition commit is before the fix stylint issues commit -5965968 @vickymarz

**Comment by vickymarz** [comment]
Screenshot_20230306-213131

**Comment by vickymarz** [comment]
The transition commit was the last commit i saw after the review. The linters passed before the review but then you pushed changes with failed linters. 

Kindly ensure that you have made all necessary changes before you submit for review to avoid this kind of cunfusion. Please kindly create another pull request. Your project was invalidated, so you can still submit again

**Comment by vickymarz** [comment]
Also, always make sure that your review has been approved on the dashboard before merging because a reviewer can actually make mistake approving your Pr, instead of invalidating or requesting changes

**Comment by ikennarichard** [comment]
Please, I made a new request https://github.com/ikennarichard/my-portfolio/pull/10, but I'm thinking that I'm to submit it here because the review said it's invalid @vickymarz

**Comment by vickymarz** [comment]
Submit on your dashboard 😄

**Pull request merged**
